---
title: "likert"
format: gfm
---

```{r}
library(readr)
library(dplyr)
library(tidyr)
library(Manu)
library(ggplot2)
library(likert)
library(HH)
```

```{r}
prepilot <- read_csv("data/dmp-prepilot.csv", locale = locale(encoding = "latin1"))
postpilot <- read_csv("data/dmp-postpilot.csv", locale = locale(encoding = "latin1"))
```

```{r}
# Reshape prepilot data

prepilot <- prepilot |> 
  select(c(1, 14:19, 21, 35:40))

prepilot_long <- prepilot |> 
  pivot_longer(-ID, names_to = "question") |> 
  group_by(question) |> 
  count(value) |> 
  group_by(question) |> 
  mutate(
    total = sum(n),
    pc = n/total,
  )

prepilot_wide <- prepilot_long |>
  pivot_wider(-c(n, total), names_from = value, values_from = pc)
  
colnames(prepilot_wide)[1] = "Item"

prepilot_wide[is.na(prepilot_wide)] <- 0

prepilot_wide <- prepilot_wide[, c(1, 5, 4, 2, 3, 6)]
```


```{r}
# Reshape postpilot data

postpilot <- postpilot |> 
  select(-1)

postpilot <- postpilot[-(13:25),]

postpilot_long <- postpilot |> 
  pivot_longer(cols = everything(), names_to = "question") |> 
  group_by(question) |> 
  count(value) |> 
  group_by(question) |> 
  mutate(
    total = sum(n),
    pc = n/total,
  )

postpilot_wide <- postpilot_long |>
  pivot_wider(-c(n, total), names_from = value, values_from = pc)
  
colnames(postpilot_wide)[1] = "Item"

postpilot_wide[is.na(postpilot_wide)] <- 0

postpilot_wide <- postpilot_wide[, c(1, 5, 4, 2, 3, 6)]
```

```{r}
# ggplot
# can't get it centered

ggplot(prepilot_long, aes(x = question , y = pc, fill = value)) +
  geom_bar(stat="identity", width = 0.7) +
  scale_fill_manual(values = get_pal("Tui")) +
  coord_flip() +
  ylab("%") +
  xlab("") +
  theme_classic()
```

```{r}
# likert
# won't run without a column called 'neutral'

plot(likert(summary = prepilot_wide)) 

```

```{r}
# HH

likert(Item~., prepilot_wide, ReferenceZero=3, ylab = "", xlab = "", auto.key = list(columns = 1, reverse.rows = T), main = "Title")

likert(Item~., postpilot_wide, ReferenceZero=3, ylab = "", xlab = "", auto.key = list(columns = 1, reverse.rows = T), main = "Title")
```


